mutation CreatePublicMovieList($name: String!, $description: String) @auth(level: PUBLIC, insecureReason: "This operation is safe to expose to the public") {
  movieList_insert(data: {
    name: $name,
    description: $description,
    isPublic: true,
    userId_expr: "uuidV4()",
    createdAt_expr: "request.time",
    updatedAt_expr: "request.time"
  })
}

query ListPublicMovieLists @auth(level: PUBLIC, insecureReason: "This operation is safe to expose to the public") {
  movieLists(where: {isPublic: {eq: true}}) {
    id
    name
    description
  }
}

mutation AddMovieToList($movieListId: UUID!, $movieId: UUID!, $note: String, $position: Int!) @auth(level: USER) {
  movieListEntry_insert(data: {
    movieListId: $movieListId,
    movieId: $movieId,
    note: $note,
    position: $position
  })
}

query ListMoviesInList($movieListId: UUID!) @auth(level: USER) {
  movieList(id: $movieListId) {
    movieListEntries_on_movieList {
      movie {
        id
        title
        year
      }
      note
      position
    }
  }
}