// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-IJ979UMdA4BJeH2zsPQOe9yNW18PxYg',
    appId: '1:314923488171:web:a1d494c389c229d8caf8ee',
    messagingSenderId: '314923488171',
    projectId: 'chafin-23cad',
    authDomain: 'chafin-23cad.firebaseapp.com',
    databaseURL: 'https://chafin-23cad-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'chafin-23cad.firebasestorage.app',
    measurementId: 'G-SMVWN2SEQT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAv5jww8KkcBDZaBpov_g_tpohAc2A-n28',
    appId: '1:314923488171:android:5c7c7eea378b91a3caf8ee',
    messagingSenderId: '314923488171',
    projectId: 'chafin-23cad',
    databaseURL: 'https://chafin-23cad-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'chafin-23cad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwiL_m8Q5FrxS-1LK0ZSj_z_CxuT-i_pU',
    appId: '1:314923488171:ios:e0bec6cefaee3d32caf8ee',
    messagingSenderId: '314923488171',
    projectId: 'chafin-23cad',
    databaseURL: 'https://chafin-23cad-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'chafin-23cad.firebasestorage.app',
    iosBundleId: 'com.chafin.chafinLoans',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwiL_m8Q5FrxS-1LK0ZSj_z_CxuT-i_pU',
    appId: '1:314923488171:ios:e0bec6cefaee3d32caf8ee',
    messagingSenderId: '314923488171',
    projectId: 'chafin-23cad',
    databaseURL: 'https://chafin-23cad-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'chafin-23cad.firebasestorage.app',
    iosBundleId: 'com.chafin.chafinLoans',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-IJ979UMdA4BJeH2zsPQOe9yNW18PxYg',
    appId: '1:314923488171:web:bb0edf64e504c6c2caf8ee',
    messagingSenderId: '314923488171',
    projectId: 'chafin-23cad',
    authDomain: 'chafin-23cad.firebaseapp.com',
    databaseURL: 'https://chafin-23cad-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'chafin-23cad.firebasestorage.app',
    measurementId: 'G-6WTPGWN6LB',
  );

}